# Brewfile
# Just run `brew tap homebrew/boneyard && brew bundle` in the same directory to have it run
#
# Need Homebrew?
# Run `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
# Or on a Linux box, run `ruby -e "$(wget -O- https://raw.github.com/Homebrew/linuxbrew/go/install)"`

tap 'caskroom/cask'

install 'ag'
install 'autoconf'
install 'autojump'
install 'automake'
install 'caskroom/cask/brew-cask'
install 'cloc'
install 'cmake'
install 'fasd'
install 'freetype'
install 'gifsicle'
install 'git'
install 'graphicsmagick'
install 'hub'
install 'imagemagick' --disable-openmp --build-from-source
install 'jpeg'
install 'libpng'
install 'libtool'
install 'mercurial'
install 'node'
install 'pkg-config'
install 'pngquant'
install 'pow'
install 'rbenv'
install 'vim'
install 'wifi-password'
install 'wget'
install 'xz'
install 'youtube-dl'
install 'zsh'

cask install 'adobe-creative-cloud'
cask install 'alfred'
cask install 'bartender'
cask install 'beamer'
cask install 'chromium --force'
cask install 'cleanmymac'
cask install 'colorpicker-skalacolor'
cask install 'dropbox'
cask install 'firefox'
cask install 'firefox-nightly --force'
cask install 'flux'
cask install 'google-chrome'
cask install 'google-chrome-canary'
cask install 'grandtotal'
cask install 'heroku-toolbelt'
cask install 'imageoptim'
cask install 'jadengeller-helium'
cask install 'kaleidoscope'
cask install 'knock'
cask install 'licecap'
cask install 'java'
cask install 'miro-video-converter'
cask install 'processing'
cask install 'screenflow'
cask install 'sequel-pro'
cask install 'skype'
cask install 'slack'
cask install 'sublime-text'
cask install 'subtitles'
cask install 'teamviewer'
cask install 'torbrowser'
cask install 'tower'
cask install 'tripmode'
cask install 'transmission'
cask install 'vagrant'
cask install 'virtualbox'
cask install 'virtualhostx'
cask install 'vlc'
cask install 'webkit-nightly --force'
